micronaut:
  application:
    name: micronaut-kafka-producer-demo
  server:
    port: 9090

endpoints:
  health:
    sensitive: false

kafka:
  schema:
    registry:
      url: http://localhost:8081
  bootstrap:
    servers:
      - localhost:29092
  producers:
    default:
      key.serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer